import os
from pathlib import Path
import shutil
from astrodown.quarto import move_quarto_resources_to_public, adjust_resource_links


analysis_dir = "analysis"
data_dir = "data"

output_dir = (
    "src/content"
    if os.getenv("QUARTO_PROJECT_OUTPUT_DIR") is None
    else os.getenv("QUARTO_PROJECT_OUTPUT_DIR")
)

move_quarto_resources_to_public(Path(output_dir, analysis_dir))
move_quarto_resources_to_public(Path(output_dir, data_dir))
# move reamining html dependencies generated by usage of htmlwidgets
move_quarto_resources_to_public(Path(data_dir))
move_quarto_resources_to_public(Path(analysis_dir))

if os.getenv("QUARTO_PROJECT_OUTPUT_FILES") is not None:
    output_files = os.getenv("QUARTO_PROJECT_OUTPUT_FILES").split("\n")
    for file in output_files:
        move_quarto_resources_to_public("src/content")
        adjust_resource_links(file)
        if file == "src/content/index.md":
            dst = "src/pages/index.md"
            if os.path.exists(dst):
                os.remove(dst)
            shutil.move(file, "src/pages")
